/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: /client/simpleswig.i

package Simple

// #cgo LDFLAGS: -L. -lsimpleswig -lsimple_library_static
/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_Simple_eed7142b84709121(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_Simple_eed7142b84709121(swig_intgo arg1);
extern uintptr_t _wrap_new_Simple_Simple_eed7142b84709121(void);
extern void _wrap_Simple_sprout_Simple_eed7142b84709121(uintptr_t arg1);
extern void _wrap_delete_Simple_Simple_eed7142b84709121(uintptr_t arg1);
#undef intgo
*/
import "C"

import (
	_ "runtime/cgo"
	"sync"
	"unsafe"
)

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

func getSwigcptr(v interface{ Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}

type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_Simple_eed7142b84709121(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_Simple_eed7142b84709121(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrSimple uintptr

func (p SwigcptrSimple) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSimple) SwigIsSimple() {
}

func NewSimple() (_swig_ret Simple) {
	var swig_r Simple
	swig_r = (Simple)(SwigcptrSimple(C._wrap_new_Simple_Simple_eed7142b84709121()))
	return swig_r
}

func (arg1 SwigcptrSimple) Sprout() {
	_swig_i_0 := arg1
	C._wrap_Simple_sprout_Simple_eed7142b84709121(C.uintptr_t(_swig_i_0))
}

func DeleteSimple(arg1 Simple) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Simple_Simple_eed7142b84709121(C.uintptr_t(_swig_i_0))
}

type Simple interface {
	Swigcptr() uintptr
	SwigIsSimple()
	Sprout()
}
